name: SellAll
main: Astro\SellAll\SellAll
version: 1.5.5+dev
api: 5.0.0
load: POSTWORLD
author: ItzXila & Astro 
description: Sell all items in your hand or all items in your inventory with the same type as in your hand

commands:
 sell:
  description: "Sell command"
  usage: "/sell all|hand|inventory"
  permission: sellall.command

permissions:
 sellall.command:
  default: true
  description: "Allows the use of /sell"
 sellall.reload:
  default: op
  description: "Reloads the plugin"
